var Const={MAX_URI_LEN:1800,MAX_SOURCE_LEN:5E3,NL:"\r\n",NL2:"\r\n\r\n"},Capability={TRANSLATE:1,DETECT_LANGUAGE:2,LISTEN:4,DICTIONARY:8},HttpMethod={UNDEFINED:0,GET:1,POST:2},CodePage={WINDOWS1251:1251,UTF8:65001,ISO8859_1:28591},toString=Object.prototype.toString,isArray=Array.isArray||function(a){return"[object Array]"===toString.call(a)};function ServiceHeader(a,b,c,d){this.id=a;this.name=b||"";this.info=c||"";this.capabilities=d}
function RequestData(a,b,c,d,e,g){this.method=a;this.uri=b||"";this.data=c||"";this.headers=d||(a===HttpMethod.UNDEFINED?"":a===HttpMethod.GET?getHeader():postHeader());this.codepage=e||CodePage.UTF8;this.responseHandler=g||""}var _linkState={links:[]};function _linkHtml(a){return String(a||"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;")}function _linkAttr(a,b){a=String(a||"");b=(b||"").toLowerCase()+"=";var c=a.toLowerCase(),d=c.indexOf(b);if(d<0)return"";d+=b.length;while(d<a.length&&/\s/.test(a.charAt(d)))d++;if(d>=a.length)return"";if(a.charAt(d)=="\""||a.charAt(d)=="'"){var e=a.charAt(d),f=a.indexOf(e,d+1);return f>=0?a.slice(d+1,f):""}var g=/^[^\s>]+/.exec(a.slice(d));return g?g[0]:""}function _linkToken(a,b){return "__QT"+a+b+"__"}function _linkOpenToken(a){return _linkToken("OPEN",a)}function _linkCloseToken(a){return _linkToken("CLOSE",a)}function _linkRefToken(a){return _linkToken("LINK",a)}function _linkNeedsStop(a,b){for(;a<b.length&&(b.charAt(a)===" "||b.charAt(a)==="\t");)a++;return a>=b.length||b.charAt(a)==="\r"||b.charAt(a)==="\n"}function prepareLinkedSource(a){_linkState.links=[];a=prepareSource(a||"").replace(/<a\b([^>]*)>([\s\S]*?)<\/a>/gi,function(a,b,c,d,e){var f,g;c=stripHtml(unquoteHtml(c||"")).replace(/\r\n/g,"\n").replace(/^\s+|\s+$/g,"");f=_linkAttr(b,"href");return c&&f?(g=_linkState.links.length+1,_linkState.links.push(f),c+" "+_linkRefToken(g)+(_linkNeedsStop(d+a.length,e)?".":"")):c||f||_linkAttr(b,"title")||_linkAttr(b,"aria-label")||_linkAttr(b,"data-text")||""});return a.replace(/(^|[\s>])([^\r\n<>]*?)([^\s<>()]+)\s*\(((?:https?:\/\/|www\.)[^()\s]+)\)/g,function(a,b,c,d,e,f,g){var h=_linkState.links.length+1;_linkState.links.push(e);return b+c+d+" "+_linkRefToken(h)+(_linkNeedsStop(f+a.length,g)?".":"")})}function _linkRestore(a){if(!a)return a||"";if(!/__(?:QTLINK|QTOPEN|QTCLOSE)\d+__/.test(a))return a||"";a=_linkHtml(a).replace(/\r\n|\r|\n/g,"<br/>");for(var b=0;b<_linkState.links.length;b++){var c=_linkHtml(_linkState.links[b]),d=_linkRefToken(b+1).replace(/[-\/\\^$*+?.()|[\]{}]/g,"\\$&");a=a.replace(new RegExp('([^\\s<>.,;:!?()\\[\\]{}]+\\s+(?:Sie|sie|SIE))([.,;:!?]*)\\s*'+d,"g"),'<a href="'+c+'">$1</a>$2');a=a.replace(new RegExp('([^\\s<>.,;:!?()\\[\\]{}]+)([.,;:!?]*)\\s*'+d,"g"),'<a href="'+c+'">$1</a>$2');a=a.replace(new RegExp(d+"\\s*([^\\s<>.,;:!?()\\[\\]{}]+)([.,;:!?]*)","g"),'<a href="'+c+'">$1</a>$2');a=a.replace(new RegExp(d,"g"),"");a=a.replace(new RegExp(_linkOpenToken(b+1),"g"),'<a href="'+c+'">');a=a.replace(new RegExp(_linkCloseToken(b+1),"g"),"</a>")}return a}function ResponseData(a,b,c,d,e){this.translation=_linkRestore(a||"");this.sourceLanguage=b;this.translationLanguage=c;this.data=d||"";this.nextRequestHandler=e||""}var Options={};function addOption(a,b){Options[a]=b}
function getHeader(){var a=format("Accept-Language: {0};q=0.8,en-US;q=0.6,en;q=0.4",Options.LanguageCode);return"Accept: */*"+Const.NL+a+Const.NL+"Accept-Encoding: gzip,deflate"+Const.NL+"Accept-Charset: utf-8"}function postHeader(a){a=a?"application/json":"application/x-www-form-urlencoded";return getHeader()+Const.NL+"Content-Type: "+a+"; charset=utf-8"}function encodeUriParam(a){return a?encodeURIComponent(a):""}
function encodeGetParam(a){a=encodeUriParam(a);if(a.length>Const.MAX_URI_LEN){a=a.slice(0,Const.MAX_URI_LEN);var b=a.lastIndexOf("%20");if(0<b)return a.slice(0,b)}return a}function encodePostParam(a){return encodeUriParam(a)}function prepareSource(a){return(a||"").replace(/(\r\n|\r)/g,"\n")}function limitSource(a,b){b=b||Const.MAX_SOURCE_LEN;return a&&a.length>b?a.slice(0,b):a}
function format(){for(var a=arguments[0],b=0;b<arguments.length-1;b++)a=a.replace(new RegExp("\\{"+b+"\\}","gm"),arguments[b+1]);return a}function stringFind(a,b){if(b)if("string"===typeof b){var c=a.indexOf(b);if(-1<c)return{index:c,length:b.length}}else if(c=a.match(b))return{index:c.index,length:c[0].length}}function stringFindSub(a,b,c,d,e){return a&&b&&d&&(b=stringFind(a,b))&&(a=a.slice(c?b.index:b.index+b.length),b=stringFind(a,d))?a.slice(0,e?b.index+b.length:b.index):""}
function trimString(a){return a?a.replace(/(^\s+)|(\s+$)/g,""):""}function startsWith(a,b){return a.slice(0,b.length)===b}function endsWith(a,b){return-1!==a.indexOf(b,a.length-b.length)}function removeIfStartsWith(a,b){return startsWith(a,b)?a.slice(b.length):a}var IE_SPLIT_ISSUE=3!=="a'b".split(/(')/g).length;
function stringSplit(a,b){if(!IE_SPLIT_ISSUE)return a.split(b);var c=[];b.global=!0;for(var d=b.exec(a);d;){c.push(a.substring(0,d.index));for(var e=1,g=d.length;e<g;e++)c.push(d[e]);a=a.substring(b.lastIndex,a.length);d=b.exec(a)}c.push(a);return c}function unquoteHtml(a){if(!a)return"";a=a.replace(/&amp[;]?/g,"&");a=a.replace(/&lt[;]?/g,"<");a=a.replace(/&gt[;]?/g,">");a=a.replace(/&quot[;]?/g,'"');return a=a.replace(/&#[0]?39[;]/g,"'")}
function removeEmptyLines(a){if(!a)return"";a=a.replace(/\r/gi,"");a=a.split("\n");for(var b=0;b<a.length;b++)a[b].match(/[\S]/g)||(a[b]="");a=a.join("\n").replace(/\n{3,}/g,"\n\n");a=a.replace(/\n/gi,Const.NL);return trimString(a)}
function stripHtml(a){if(!a)return"";a=a.replace(/\x3c!--[\s\S]*?--\x3e/g,"");a=a.replace(/<(style|script)(.|\s)*?(style|script)>/g,"");a=a.replace(/<br\/>/gi,Const.NL);a=a.replace(/<[^>]+>/g,"");a=a.replace(/&nbsp;/g," ");a=a.replace(/&#x27;/gi,"'");a=a.replace(/ +(?= )/g,"");return removeEmptyLines(a)}function regExpRemove(a,b,c){if(!b)return a;b=format(c,b.join("|"));return a.replace(new RegExp(b,"g"),"")}
function removeAttributes(a,b){return regExpRemove(a,b," ({0})(?:\\s*=\\s*(?:(?:\"((?:\\.|[^\"])*)\")|(?:'((?:\\.|[^'])*)')|([^>\\s]+)))?")}function removeTags(a,b){return regExpRemove(a,b,"</?({0})[^>]*>")}function removeElements(a,b){return regExpRemove(a,b,"<\\s*({0})[^>]*>((.|\n)*?)<\\s*/\\s*({0})>")}
function updateHtmlLinks(a,b){if(!a)return"";var c=startsWith(b,"https")?"https://":"http://";b=removeIfStartsWith(b,c);endsWith(b,"/")||(b+="/");a=a.replace(/href="\/\//gi,'href="'+c);a=a.replace(/href="\//gi,'href="'+c+b);a=a.replace(/src="\/\//gi,'src="'+c);a=a.replace(/src="\//gi,'src="'+c+b);a=a.replace(/href='\/\//gi,"href='"+c);a=a.replace(/href='\//gi,"href='"+c+b);a=a.replace(/src='\/\//gi,"src='"+c);return a=a.replace(/src='\//gi,"src='"+c+b)}
var SupportedLanguages=null,UNKNOWN_LANGUAGE_CODE=-1,UNKNOWN_LANGUAGE=0,AUTO_DETECT_LANGUAGE=1,ENGLISH_LANGUAGE=17;function isLanguage(a){return a>AUTO_DETECT_LANGUAGE&&a<SupportedLanguages.length}function codeFromLanguage(a){return a===AUTO_DETECT_LANGUAGE||isLanguage(a)?SupportedLanguages[a]:UNKNOWN_LANGUAGE_CODE}
function languageFromCode(a){if(SupportedLanguages[ENGLISH_LANGUAGE]===a)return ENGLISH_LANGUAGE;for(var b=AUTO_DETECT_LANGUAGE;b<SupportedLanguages.length;b++)if(SupportedLanguages[b]===a)return b;return UNKNOWN_LANGUAGE}function usesAutoDetectCode(){return SupportedLanguages[AUTO_DETECT_LANGUAGE]!==UNKNOWN_LANGUAGE_CODE}function parseJSON(a){return(new Function("return "+a))()}
var stringifyJSON=function(){var a={'"':'\\"',"\\":"\\\\","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t"},b=function(b){return a[b]||"\\u"+(b.charCodeAt(0)+65536).toString(16).substr(1)},c=/[\\"\u0000-\u001F\u2028\u2029]/g;return function e(a){if(null===a)return"null";if("number"===typeof a)return isFinite(a)?a.toString():"null";if("boolean"===typeof a)return a.toString();if("object"===typeof a){if("function"===typeof a.toJSON)return e(a.toJSON());if(isArray(a)){for(var h="[",f=0;f<a.length;f++)h+=
(f?", ":"")+e(a[f]);return h+"]"}if("[object Object]"===toString.call(a)){h=[];for(f in a)a.hasOwnProperty(f)&&h.push(e(f)+": "+e(a[f]));return"{"+h.join(", ")+"}"}}return'"'+a.toString().replace(c,b)+'"'}}();Array.prototype.map||(Array.prototype.map=function(a){for(var b=Object(this),c=b.length>>>0,d=Array(c),e=0;e<c;)e in b&&(d[e]=a(b[e],e,b)),e++;return d});Array.prototype.forEach||(Array.prototype.forEach=function(a){for(var b=Object(this),c=b.length>>>0,d=0;d<c;)d in b&&a(b[d],d,b),d++});
Array.prototype.filter||(Array.prototype.filter=function(a){for(var b=Object(this),c=b.length>>>0,d=0,e=[],g;d<c;)d in b&&(g=b[d],a(g,d,b)&&e.push(g)),d++;return e});
function prepareLinkedSource(a){_linkState.links=[];a=prepareSource(a||"").replace(/<a\b([^>]*)>([\s\S]*?)<\/a>/gi,function(a,b,c,d,e){var f,g;c=stripHtml(unquoteHtml(c||"")).replace(/\r\n/g,"\n").replace(/^\s+|\s+$/g,"");f=_linkAttr(b,"href");return c&&f?(g=_linkState.links.length+1,_linkState.links.push(f),c+" "+_linkRefToken(g)+(_linkNeedsStop(d+a.length,e)?".":"")):c||f||_linkAttr(b,"title")||_linkAttr(b,"aria-label")||_linkAttr(b,"data-text")||""});return a.replace(/(^|[\s>])([^\r\n<>]*?)([^\s<>()]+)\s*\(((?:https?:\/\/|www\.)[^()\s]+)\)/g,function(a,b,c,d,e,f,g){var h=_linkState.links.length+1;_linkState.links.push(e);return b+c+d+" "+_linkRefToken(h)+(_linkNeedsStop(f+a.length,g)?".":"")})}

_linkState={links:[],texts:[]};
function _linkAdd(a,b){_linkState.links.push(a);_linkState.texts.push(b||"");return _linkState.links.length}
function _linkRx(a){return String(a||"").replace(/[-\/\\^$*+?.()|[\]{}]/g,"\\$&")}
function _linkBadAnchor(a){a=String(a||"").toLowerCase();return /^(?:com|org|net|ru|de|ai|www|http|https|googleapis|translate-pa|pa|lingva|nex)$/.test(a)||0<=a.indexOf(".")}
function _linkFallbackText(a){a=_linkState.texts&&_linkState.texts[a]||"";return /чит/i.test(a)?"READ":a||"LINK"}
function prepareLinkedSource(a){_linkState={links:[],texts:[]};a=prepareSource(a||"").replace(/<a\b([^>]*)>([\s\S]*?)<\/a>/gi,function(a,b,c,d,e){var f,g;c=stripHtml(unquoteHtml(c||"")).replace(/\r\n/g,"\n").replace(/^\s+|\s+$/g,"");f=_linkAttr(b,"href");return c&&f?(g=_linkAdd(f,c),c+" "+_linkRefToken(g)+(_linkNeedsStop(d+a.length,e)?".":"")):c||f||_linkAttr(b,"title")||_linkAttr(b,"aria-label")||_linkAttr(b,"data-text")||""});return a.replace(/(^|[\s>])([^\r\n<>]*?)([^\s<>()]+)\s*\(((?:https?:\/\/|www\.)[^()\s]+)\)/g,function(a,b,c,d,e,f,g){var h=_linkAdd(e,d);return b+c+d+" "+_linkRefToken(h)+(_linkNeedsStop(f+a.length,g)?".":"")})}
function _linkRestore(a){if(!a)return a||"";if(!/__(?:QTLINK|QTOPEN|QTCLOSE)\d+__/.test(a))return a||"";a=_linkHtml(a).replace(/\r\n|\r|\n/g,"<br/>");for(var b=0;b<_linkState.links.length;b++){var c=_linkHtml(_linkState.links[b]),d=_linkRx(_linkRefToken(b+1)),e='<a href="'+c+'">',f="</a>",g="(?:READ|Read|read|LESEN|Lesen|lesen|ЧИТАТЬ)(?:\\s+(?:SIE|Sie|sie))?";a=a.replace(new RegExp("("+g+")([.,;:!?]*)\\s*"+d+"(?:[A-Za-zА-Яа-я]{1,8})?","g"),e+"$1"+f+"$2");a=a.replace(new RegExp(d+"\\s*("+g+")([.,;:!?]*)","g"),e+"$1"+f+"$2");a=a.replace(new RegExp('([^\\s<>.,;:!?()\\[\\]{}]+)([.,;:!?]*)\\s*'+d+'([A-Za-zА-Яа-я]{0,8})?',"g"),function(a,g,h,i){return _linkBadAnchor(g)?g+h+" "+e+_linkHtml(_linkFallbackText(b))+f:g+h});a=a.replace(new RegExp(d,"g"),"");a=a.replace(new RegExp(_linkOpenToken(b+1),"g"),e);a=a.replace(new RegExp(_linkCloseToken(b+1),"g"),f)}return a}
function _linkRepairMisplacedUrls(a){return String(a||"").replace(/ЧИ\s*\(((?:https?:\/\/|www\.)[^()\s]+)\)\s*ТАТЬ/g,"ЧИТАТЬ ($1)").replace(/([^\r\n()]{0,60})\s*\(((?:https?:\/\/|www\.)[^()\s]+)\)([^\r\n()]{0,60}ЧИТАТЬ)/g,function(a,b,c,d){var e;if(/ЧИТАТЬ/.test(b))return a;e=(b+d).replace(/([A-Za-z])\.\s+([A-Za-z]{2,})(\s+ЧИТАТЬ)/g,"$1.$2$3").replace(/([A-Za-z])\s+([A-Za-z]{1,20}\.[A-Za-z]{2,})(\s+ЧИТАТЬ)/g,"$1$2$3");return e.replace(/ЧИТАТЬ/,"ЧИТАТЬ ("+c+")")})}
function prepareLinkedSource(a){_linkState={links:[],texts:[]};a=_linkRepairMisplacedUrls(prepareSource(a||"")).replace(/<a\b([^>]*)>([\s\S]*?)<\/a>/gi,function(a,b,c,d,e){var f,g;c=stripHtml(unquoteHtml(c||"")).replace(/\r\n/g,"\n").replace(/^\s+|\s+$/g,"");f=_linkAttr(b,"href");return c&&f?(g=_linkAdd(f,c),c+" "+_linkRefToken(g)+(_linkNeedsStop(d+a.length,e)?".":"")):c||f||_linkAttr(b,"title")||_linkAttr(b,"aria-label")||_linkAttr(b,"data-text")||""});return a.replace(/(^|[\s>])([^\r\n<>]*?)([^\s<>()]+)\s*\(((?:https?:\/\/|www\.)[^()\s]+)\)/g,function(a,b,c,d,e,f,g){var h=_linkAdd(e,d);return b+c+d+" "+_linkRefToken(h)+(_linkNeedsStop(f+a.length,g)?".":"")})}
function _linkNormalizeDomains(a){return String(a||"").replace(/translate-pa\.(?:\s|<br\/>)+googleapis\.(?:\s|<br\/>)+com/gi,"translate-pa.googleapis.com").replace(/lingvanex\.(?:\s|<br\/>)+com/gi,"lingvanex.com")}
function _linkRestore(a){if(!a)return a||"";if(!/__(?:QTLINK|QTOPEN|QTCLOSE)\d+__/.test(a))return _linkNormalizeDomains(a||"");a=_linkHtml(a).replace(/\r\n|\r|\n/g,"<br/>");for(var b=0;b<_linkState.links.length;b++){var c=_linkHtml(_linkState.links[b]),d=_linkRx(_linkRefToken(b+1)),e='<a href="'+c+'">',f="</a>",g="(?:READ|Read|read|LESEN|Lesen|lesen|ЧИТАТЬ)(?:\\s+(?:SIE|Sie|sie))?";a=a.replace(new RegExp("("+g+")([.,;:!?]*)\\s*"+d+"(?:[A-Za-zА-Яа-я]{1,8})?","g"),e+"$1"+f+"$2");a=a.replace(new RegExp(d+"\\s*("+g+")([.,;:!?]*)","g"),e+"$1"+f+"$2");a=a.replace(new RegExp('([^\\s<>.,;:!?()\\[\\]{}]+)([.,;:!?]*)\\s*'+d+'([A-Za-zА-Яа-я]{0,8})?',"g"),function(a,g,h,i){return _linkBadAnchor(g)?g+h+" "+e+_linkHtml(_linkFallbackText(b))+f:g+h});a=a.replace(new RegExp(d,"g"),"");a=a.replace(new RegExp(_linkOpenToken(b+1),"g"),e);a=a.replace(new RegExp(_linkCloseToken(b+1),"g"),f)}return _linkNormalizeDomains(a)}
function _linkRepairMisplacedUrls(a){return String(a||"").replace(/ЧИ\s*\(((?:https?:\/\/|www\.)[^()\s]+)\)\s*ТАТЬ/g,"ЧИТАТЬ ($1)").replace(/([A-Za-z.-]+)\s*\(((?:https?:\/\/|www\.)[^()\s]+)\)\s*(com\s+ЧИТАТЬ)/g,function(a,b,c,d){return(b+"."+d).replace(/\.\.+/g,".").replace(/\.\s*com/,".com").replace(/ЧИТАТЬ/,"ЧИТАТЬ ("+c+")")}).replace(/([A-Za-z]+)\s*\(((?:https?:\/\/|www\.)[^()\s]+)\)\s*(nex\.com\s+ЧИТАТЬ)/g,function(a,b,c,d){return(b+d).replace(/ЧИТАТЬ/,"ЧИТАТЬ ("+c+")")})}
function prepareLinkedSource(a){_linkState={links:[],texts:[]};a=_linkRepairMisplacedUrls(prepareSource(a||"")).replace(/<a\b([^>]*)>([\s\S]*?)<\/a>/gi,function(a,b,c,d,e){var f,g;c=stripHtml(unquoteHtml(c||"")).replace(/\r\n/g,"\n").replace(/^\s+|\s+$/g,"");f=_linkAttr(b,"href");return c&&f?(g=_linkAdd(f,c),c+" "+_linkRefToken(g)+(_linkNeedsStop(d+a.length,e)?".":"")):c||f||_linkAttr(b,"title")||_linkAttr(b,"aria-label")||_linkAttr(b,"data-text")||""});return a.replace(/(^|[\s>])([^\s<>()]+)\s*\(((?:https?:\/\/|www\.)[^()\s]+)\)/g,function(a,b,c,d,e,f){var g=_linkAdd(d,c);return b+c+" "+_linkRefToken(g)+(_linkNeedsStop(e+a.length,f)?".":"")})}
function _linkPlain(a){return String(a||"").replace(/<br\s*\/?>/gi,Const.NL).replace(/<a\b[^>]*>([\s\S]*?)<\/a>/gi,"$1").replace(/<\/?[^>]+>/g,"")}
function _linkRestore(a){if(!a)return a||"";a=_linkPlain(_linkNormalizeDomains(a||""));if(!/__(?:QTLINK|QTOPEN|QTCLOSE)\d+__/.test(a))return a;for(var b=0;b<_linkState.links.length;b++){var c=_linkRx(_linkRefToken(b+1)),d="(?:READ|Read|read|LESEN|Lesen|lesen|ЧИТАТЬ)(?:\\s+(?:SIE|Sie|sie))?";a=a.replace(new RegExp("("+d+")([.,;:!?]*)\\s*"+c+"(?:[A-Za-zА-Яа-я]{1,8})?","g"),"$1$2");a=a.replace(new RegExp(c+"\\s*("+d+")([.,;:!?]*)","g"),"$1$2");a=a.replace(new RegExp('([^\\s<>.,;:!?()\\[\\]{}]+)([.,;:!?]*)\\s*'+c+'([A-Za-zА-Яа-я]{0,8})?',"g"),function(a,c,d,e){return _linkBadAnchor(c)?c+d+" "+_linkFallbackText(b):c+d});a=a.replace(new RegExp(c,"g"),"");a=a.replace(new RegExp(_linkOpenToken(b+1),"g"),"");a=a.replace(new RegExp(_linkCloseToken(b+1),"g"),"")}return _linkPlain(_linkNormalizeDomains(a))}
function escapeRegExp(a){return String(a||"").replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}
function _linkSymbolicAnchor(a){return /^[\[(][^\]\)\r\n]{1,16}[\])]$/.test(String(a||""))}
function _linkRestore(a){if(!a)return a||"";a=_linkPlain(_linkNormalizeDomains(a||""));for(var b=0;b<_linkState.links.length;b++){var c=escapeRegExp(_linkRefToken(b+1)),u=_linkState.urls&&_linkState.urls[b]||_linkState.links[b]||"",d="(?:READ|Read|read|LESEN|Lesen|lesen|ЧИТАТЬ)(?:\\s+(?:SIE|Sie|sie))?",v=trimString(_linkState.texts&&_linkState.texts[b]||""),w=escapeRegExp(v),x=escapeRegExp(u),y="[A-Za-zА-Яа-яЁё]{1,8}\\)?",z=false;if(v&&_linkSymbolicAnchor(v)){var r=a;a=a.replace(new RegExp(c+"(?:"+y+")?\\s*("+w+")","g"),"$1 ("+u+")");a=a.replace(new RegExp("("+w+")\\s*"+c+"(?:"+y+")?","g"),"$1 ("+u+")");z=a!==r}if(!z&&/__(?:QTLINK|QTOPEN|QTCLOSE)\d+__/.test(a)){a=a.replace(new RegExp("("+d+")([.,;:!?]*)\\s*"+c+"(?:[A-Za-zА-Яа-я]{1,8})?","g"),"$1 ("+u+")$2");a=a.replace(new RegExp(c+"\\s*("+d+")([.,;:!?]*)","g"),"$1 ("+u+")$2");a=a.replace(new RegExp('([^\\s<>.,;:!?()\\[\\]{}]+)([.,;:!?]*)\\s*'+c+'([A-Za-zА-Яа-я]{0,8})?',"g"),function(a,c,d,e){return _linkBadAnchor(c)?c+d+" "+_linkFallbackText(b)+" ("+u+")":c+d+" ("+u+")"});a=a.replace(new RegExp(c,"g"),"");a=a.replace(new RegExp(escapeRegExp(_linkOpenToken(b+1)),"g"),"");a=a.replace(new RegExp(escapeRegExp(_linkCloseToken(b+1)),"g"),"")}if(v&&u)a=a.replace(new RegExp("("+w+"\\s*\\("+x+"\\))"+y+"(?=\\s|$|[.,;:!?])","g"),"$1")}a=_linkPlain(_linkNormalizeDomains(a));if(_linkState&&_linkState.texts){for(var __qtCleanI=0;__qtCleanI<(_linkState.urls&&_linkState.urls.length||_linkState.links&&_linkState.links.length||0);__qtCleanI++){var __qtCleanAnchor=trimString(_linkState.texts[__qtCleanI]||""),__qtCleanUrl=_linkState.urls&&_linkState.urls[__qtCleanI]||_linkState.links&&_linkState.links[__qtCleanI]||"";if(!__qtCleanAnchor||!__qtCleanUrl)continue;a=a.replace(new RegExp(escapeRegExp(__qtCleanAnchor)+"\\s*\\("+escapeRegExp(__qtCleanUrl)+"\\)"+"[A-Za-zА-Яа-яЁё]{1,8}\\)?"+"(?=\\s|$|[.,;:!?])","g"),__qtCleanAnchor+" ("+__qtCleanUrl+")")}}return a}
