var _qtRD=ResponseData;function _qtErrPrefix(a){a=a||"";return /^\s*\[E\]/.test(a)?a:"[E] "+(a||"Keine Daten zurueckgegeben.")}ResponseData=function(a,b,c,d,e){if(!e){var f=a||"";if(!f||(!/^\s*\[E\]/.test(f)&&/^(?:\s*(?:DeepL|YandexInL|Yandex|Google|Microsoft|FreeTranslations|WebTran|TranslateEU|TranslatorEU|Lingvanex|LaraTranslate|Wikipedia|Multi)\s*:\s*)?(?:keine |Keine |Fehler|Error|Skript-Fehler|Zeit|unsupported|failed|timeout|unavailable|no usable|no data|empty)/i.test(f)))a=_qtErrPrefix(f)}_qtRD.call(this,a,b,c,d,e)};
function serviceHeader(){return new ServiceHeader(112,"Google New","Google Translate web flow via TranslateWebserverUi batchexecute."+Const.NL2+serviceHost(),Capability.TRANSLATE|Capability.DETECT_LANGUAGE)}
function serviceHost(a,b,c){return"https://translate.google."+(Options.PreferredDomain||Options.GoogleDomain||"com")}
function serviceLink(a,b,c){var d=serviceHost()+"/";a&&(b=isLanguage(b)?codeFromLanguage(b):"auto",c=isLanguage(c)?codeFromLanguage(c):"auto",d+=format("#{0}/{1}/{2}",b,c,encodeGetParam(a)));return d}
SupportedLanguages=[-1,"auto","af","az","sq","ar","hy","eu","be","bg","ca","zh-CN","zh-TW","hr","cs","da","nl","en","et","fi","tl","fr","gl","de","el","ht","iw","hi","hu","is","id","it","ga","ja","ka","ko","lv","lt","mk","ms","mt","no","fa","pl","pt","ro","ru","sr","sk","sl","es","sw","sv","th","tr","uk","ur","vi","cy","yi","eo","hmn","la","lo","kk","uz","si","tg","te","km","mn","kn","ta","mr","bn","tt"];
var GoogleNewReqId=1E5;
function _legacyDetectRequest(a){a=limitSource(prepareLinkedSource(a));a=encodeUriParam(a);var b=a.length>Const.MAX_URI_LEN?HttpMethod.POST:HttpMethod.GET;return new RequestData(b,"/translate_a/single?client=gtx&sl=auto&dt=ld&ie=UTF-8&oe=UTF-8"+(b===HttpMethod.POST?"":"&q="+a),b===HttpMethod.POST?"q="+a:null)}
function serviceDetectLanguageRequest(a){return _legacyDetectRequest(a)}
function serviceDetectLanguageResponse(a){a=parseJSON(a);return getSourceLanguage(a)}
function _requestId(){return GoogleNewReqId+=100+Math.floor(900*Math.random())}
function _translatePath(){return format("/_/TranslateWebserverUi/data/batchexecute?rpcids=MkEWBc&_reqid={0}&rt=c",_requestId())}
function _translateBody(a,b,c){a=limitSource(prepareLinkedSource(a));b=isLanguage(b)?codeFromLanguage(b):"auto";c=codeFromLanguage(c);return"f.req="+encodePostParam(stringifyJSON([[["MkEWBc",stringifyJSON([[a,b,c,!0],[null]]),null,"generic"]]]))}
function _translateRequest(a,b,c,d){return new RequestData(HttpMethod.POST,_translatePath(),_translateBody(a,b,c),postHeader()+Const.NL+"Origin: "+serviceHost()+Const.NL+"Referer: "+serviceLink(),null,d)}
function _translateResult(a){a=prepareLinkedSource(a).split("\n");for(var b=0;b<a.length;b++){var c=trimString(a[b]);if(startsWith(c,"[["))try{c=parseJSON(c);if(c&&c[0]&&"wrb.fr"===c[0][0]&&"MkEWBc"===c[0][1])return parseJSON(c[0][2])}catch(d){}}}
function _segmentText(a){var b="",c;if(a)for(c=0;c<a.length;c++)a[c]&&0!==a[c].length&&(b+=a[c][0]||"");return b}
function _buildResponse(a,b,c){a=_translateResult(a);var d="",e;if(a&&a[1]&&(e=a[1],e[0]&&e[0][0])){d=_segmentText(e[0][0][5]);d||(d=e[0][0][0]||"");if(d)return isLanguage(b)||(b=languageFromCode(e[3]||a[2])),c=languageFromCode(e[1])||c,new ResponseData(d,b,c)}}
function serviceTranslateRequest(a,b,c){return _translateRequest(a,b,c,"serviceTranslateResponseWeb")}
function serviceTranslateRequestLegacy(a,b,c){a=limitSource(prepareLinkedSource(a));a=encodeUriParam(a);var d=a.length>Const.MAX_URI_LEN?HttpMethod.POST:HttpMethod.GET,e=format("/translate_a/single?client=gtx&sl={0}&tl={1}&hl={2}&dt=bd&dt=t&dt=ld&dt=rm&ie=UTF-8&oe=UTF-8",codeFromLanguage(b),codeFromLanguage(c),Options.LanguageCode);d===HttpMethod.GET&&(e+="&q="+a);return new RequestData(d,e,d===HttpMethod.POST?"q="+a:null)}
function serviceTranslateResponseWeb(a,b,c,d){return _buildResponse(b,c,d)||new ResponseData("",c,d,"","serviceTranslateRequestLegacy")}
function serviceTranslateResponse(a,b,c,d){a=_buildResponse(b,c,d);if(a)return a;a=parseJSON(b);var e=b="",f,g;if(a){var h=a[0];if(h)for(e=0;e<h.length;e++)(g=h[e])&&0!==g.length&&(b+=g[0]||"",2<g.length&&e===h.length-1&&(f=g[2]||""));if(h=a[1])for(e=0;e<h.length;e++)if(g=h[e],!(3>g.length)){b+=Const.NL2+g[0]+":";var l=g[2];for(g=0;g<l.length;g++){var k=l[g];1<k.length&&(b+=Const.NL+"    "+k[0],(k=k[1])&&0<k.length&&(b+=" ("+k.join(", ")+")"))}}isLanguage(c)||(c=getSourceLanguage(a))}return new ResponseData(b,c,d,f)}
function getSourceLanguage(a){return!a||9>a.length?UNKNOWN_LANGUAGE:(a=a[8])&&0!==a.length?languageFromCode(a[0][0]):UNKNOWN_LANGUAGE}
